### ISSUE TITLE
Support "open -g" on OS X

### ISSUE THREAD

**Issue by grr** [tyru/open-browser.vim#106]
On OS X, `open` has the option `-g Do not bring the application to the foreground`. Can support for this be added natively? I had added this to my .vimrc:

    let g:openbrowser_browser_commands = [{
    \ 'name': 'open',
    \ 'args': ['{browser}', '-g', '{uri}']
    \ }]

But 076ff15125eafa2bb36bbc4653c58529f8620a7e broke that by adding an undocumented cmd param. If builtin support was added for -g, we wouldn't have to worry about breakage from internal changes.

**Comment by tyru** [comment]
Sorry for breaking change.
but it is difficult to change existing behavior (adding -g parameter to open).
I will fix error when key `cmd` doesn't exist.

**Comment by tyru** [comment]
@grr Fixed breaking change. Please check it.

**Comment by grr** [comment]
Fix confirmed. Thanks.
