### ISSUE TITLE
issue with using this plugin with vimb

### ISSUE THREAD

**Issue by wsdjeg** [tyru/open-browser.vim#109]
hi @tyru thanks for this plugin.

I do not have firefox or chrome installed in my pc, the only one is vimb. when using this plugin
vim will block until vimb is closed.

vimb is : https://github.com/fanglingsu/vimb

**Comment by tyru** [comment]
What OS are you using?

**Comment by wsdjeg** [comment]
I am using archlinux.

**Comment by tyru** [comment]
sorry for silence. I moved.

Please try this:

```vim
let g:openbrowser_browser_commands = [
\   {'name': 'vimb',
\    'args': ['{browser}', '{uri}']}
]
```

Or if `vimb` is not in `$PATH`:

```vim
let g:openbrowser_browser_commands = [
\   {'name': 'vimb',
\    'cmd' : '<path to vimb>',
\    'args': ['{browser}', '{uri}']}
]
```

**Comment by wsdjeg** [comment]
@tyru 

still block vim

the issue is run `vimb https://google.com` in command-line will block terminal until the vimb windows is closed, 

BTW the vim script should be:

```
let g:openbrowser_browser_commands = [
\   {'name': 'vimb',
\    'args': ['{browser}', '{uri}']}
\    ]
```
maybe should run command like `nohup vim http://google.com &`

**Comment by tyru** [comment]
Try adding `background`:

```vim
let g:openbrowser_browser_commands = [
\   {'name': 'vimb',
\    'args': ['{browser}', '{uri}']},
\    'background': 1}
]
```

**Comment by tyru** [comment]
@wsdjeg closable?

**Comment by wsdjeg** [comment]
yeah, Thanks for your info.
