### ISSUE TITLE
gx mapping does not work

### ISSUE THREAD

**Issue by jdhao** [tyru/open-browser.vim#118]
I am using Neovim (version 0.3.4) on Windows 10 (version 1803).

I installed this plugin and use the following settings inside my  config file `init.vim`:

```
let g:netrw_nogx = 1
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
```

But the mapping does not work. The command provided (`OpenBrowser`, `OpenBrowserSearch`, `OpenBrowserSmartSearch`) works as expected though.

After changing  `gx` to other key, e.g., `ob`, I can use the map key to open the URLs.

**Comment by tyru** [comment]
Can you reproduce this now?
That config seems correct.

**Comment by jdhao** [comment]
Thanks for your remind. I tried the above settings for the latest version of this plugin. The mappings work as expected now.
