### ISSUE TITLE
[Win10] E684 error occurs in :OpenbrowserSearch

### ISSUE THREAD

**Issue by tamago324** [tyru/open-browser.vim#138]
An error occurred during the execution of `:OpenbrowserSearch`.

minvimrc

```vim
set encoding=utf-8
scriptencoding utf-8

syntax enable
filetype plugin indent on

set nocompatible

set runtimepath^=~/ghq/github.com/tyru/open-browser.vim
```

再現方法

1. `gvim.exe --clean -u minvimrc`
2. `:OpenbrowserSearch hello`
3. An error occurred.

```
function openbrowser#_cmd_search[1]..<SNR>29__OpenBrowser_cmd_search[7]..<SNR>29__OpenBrowser_search[17]..<SNR>29__OpenBrowser_open の処理中にエラーが検出されました:
行    2:
E684: リストのインデックスが範囲外です: 0
```

Also, the browser opened correctly at 57b894d.
I'm sorry, but please confirm.

**Comment by zhmars** [comment]
I can confirm this. Similar error with `OpenBrowser http://google.com/ `.

```conf
Error detected while processing function openbrowser#_cmd_open[1]..<SNR>177__OpenBrowser_cmd_open[6]..<SNR>177__OpenBrowser_open:
line    2:
E684: list index out of range: 0
```

**Comment by tyru** [comment]
I also confirmed this. I will fix it.

**Comment by tamago324** [comment]
Thanks!

**Comment by pappasam** [comment]
I confirm this on Ubuntu 18.04

**Comment by tyru** [comment]
Could you check #139 solve this?

**Comment by tyru** [comment]
ah sorry, I could confirm this problem 😅 
I confirmed this problem was fixed. closed

**Comment by tamago324** [comment]
Thank you!
