### ISSUE TITLE
Cannot open URL on Windows.

### ISSUE THREAD

**Issue by kashewnuts** [tyru/open-browser.vim#141]
## Expected
Open URL on Windows like 57b894d0aa5f800220d25fdeeccf28d8a7f6ac89.

## Environment Information

 * Plugin Version: 99b8c0b845428204c4e1a08d6e7e58ae414accb2
 * OS: Windows 10 Pro 1909
 * Vim version: 8.2.486

## Provide a minimal vimrc

```vim
" minimal.vimrc
call plug#begin('~/.cache/plugged')
" https://github.com/tyru/open-browser.vim
Plug 'tyru/open-browser.vim' ,        {'on': '<Plug>(openbrowser-smart-search)'}
call plug#end()
let g:netrw_nogx = 1 " disable netrw's gx mapping.
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
```

## How to reproduce problems from vim startup

 1. vim -Nu minimal.vimrc
 2. open minimal.vimrc
 4. focus on URL position
 5. type gx

## Screenshot

![open-browser vim-error-on-windows](https://user-images.githubusercontent.com/1122795/80969278-5274ba00-8e54-11ea-8e6e-d9ff87a4ab48.png)

**Comment by KSR-Yasuda** [comment]
I have same issue with [Previm][].

[Previm]: https://github.com/previm/previm

* OS: Windows 8.1 Pro (x64)
* Vim: [v8.2.87 (Kaoriya build)](https://github.com/koron/vim-kaoriya/releases/tag/v8.2.0087-20200106), and also v8.2.592 in Git for Windows v2.26.2.windows.1
* Plugins:
    * OpenBrowser: Commit 99b8c0b845428204c4e1a08d6e7e58ae414accb2
    * [Previm][]: Commit e42063e4ddd33c61ab47e49683113d0259a802b5

OpenBrowser commit 57b894d0aa5f800220d25fdeeccf28d8a7f6ac89 works.
The pull request #137 (commit 1765d551ccdf72f2c927e39d735f17bf95dda308) looks bad.

I think the code below is the bug point.

```diff
diff --git a/autoload/vital/__openbrowser__/OpenBrowser.vim b/autoload/vital/__openbrowser__/OpenBrowser.vim
index 35f7100..d1c7a84 100644
--- a/autoload/vital/__openbrowser__/OpenBrowser.vim
+++ b/autoload/vital/__openbrowser__/OpenBrowser.vim
@@ -58,8 +58,9 @@ function! s:new(config) abort
 endfunction
 
 " @param uri URI object or String
-function! s:_OpenBrowser_open(uri) abort dict
+function! s:_OpenBrowser_open(uri, ...) abort dict
   let uri = a:uri
+  let options = a:000[0]
   if type(uri) isnot# type('')
     call s:_throw('s:OpenBrowser.open() received non-String argument: uri = ' . string(uri))
   endif
@@ -92,6 +93,7 @@ function! s:_OpenBrowser_open(uri) abort dict
       endif
     endif
 
+    let b.cmd.args += options
     let opener = b.build()
     let failed = !opener.open()
 
```

**Comment by KSR-Yasuda** [comment]
On windows platform, `b.cmd.args` was a string.
On the other hand, it was an array on Ubuntu.

So it needs to do type check beforehand.

I'm not familiar with Vim script, so this patch may be ugly. Recheck, experts!
