### ISSUE TITLE
Remove AppVeyor's webhook

### ISSUE THREAD

**Issue by Milly** [tyru/open-browser.vim#153]
Remove AppVeyor's webhook from the project configuration.
Because AppVeyor's error  is displayed in PR. (see #152)
Now CI running on GitHub Actions. (merged #150)

**Comment by tyru** [comment]
Thanks! 🙇 
Testing on #155

**Comment by tyru** [comment]
AppVeyor didn't start. closing

**Comment by tyru** [comment]
@Milly Please re-run the PR 🙏  (rebase or re-create PR? 🤔 )

**Comment by Milly** [comment]
Thx!
