### ISSUE TITLE
E471: Argument required

### ISSUE THREAD

**Issue by pogopaule** [tyru/open-browser.vim#156]
If I press `gx` when the cursor is above an URL I get the error `E471: Argument required`. The plugin is installed via packer. Any ideas why this happens and how to fix it?

`gxx` (OpenGithubFile) works fine...

```
-- tyru/open-browser-github.vim
-- disable netrw's gx mapping.
vim.cmd([[
let g:netrw_nogx = 1
]])
map('n', 'gx', '<cmd>OpenBrowserSmartSearch<CR>', opts)
map('v', 'gx', '<cmd>OpenBrowserSmartSearch<CR>', opts)
map('n', 'gxx', '<cmd>OpenGithubFile<CR>', opts)
```

**Comment by stefanvanburen** [comment]
I think you probably want `<plug>(openbrowser-smart-search)`:

```
map('n', 'gx', '<plug>(openbrowser-smart-search)', opts)
map('v', 'gx', '<plug>(openbrowser-smart-search)', opts)
```

https://github.com/tyru/open-browser.vim/blob/80ec3f2bb0a86ac13c998e2f2c86e16e6d2f20bb/doc/openbrowser.txt#L49-L54

versus

https://github.com/tyru/open-browser.vim/blob/80ec3f2bb0a86ac13c998e2f2c86e16e6d2f20bb/doc/openbrowser.txt#L62-L63

**Comment by pogopaule** [comment]
Thank you! That solved the problem.
