### ISSUE TITLE
vimprocを有効にして#を含むURLを開く場合、#以降が無視される

### ISSUE THREAD

**Issue by hokorobi** [tyru/open-browser.vim#65]
#64 の修正で #56 が再発しているようです。
vimproc を使う場合でも uri_noesc を使うことになるためではないかと思います。

**Comment by tyru** [comment]
長い間コメントせずすみません。
今手元にWindows + Vim環境がないので少々お待ちください…

**Comment by tyru** [comment]
Windows環境でも再現＆修正を確認しました。

**Comment by hokorobi** [comment]
ありがとうございます！
修正されていることを確認しました。
