### ISSUE TITLE
Next release tag

### ISSUE THREAD

**Issue by wikimatze** [tyru/open-browser.vim#66]
Would be nice if you can create one? 

Bests

Matthias

**Comment by tyru** [comment]
Sorry for the late reply because of no Vim environment recently...

Yes, I must make the next release tag and upload to vim.org .
It is a little bit bothersome but important task...
I'll work on this task in a week if no big regression.

**Comment by tyru** [comment]
Released.
https://github.com/tyru/open-browser.vim/releases/tag/v0.1.0

**Comment by tyru** [comment]
oops, forgot to add changelog...
Added a changelog text and bump version :)
https://github.com/tyru/open-browser.vim/releases/tag/v0.1.1

**Comment by tyru** [comment]
Also I uploaded to vim.org
http://www.vim.org/scripts/script.php?script_id=3133

**Comment by wikimatze** [comment]
Thanks a lot!
