### ISSUE TITLE
g:restart_menu_lang のドキュメントが混ざっている

### ISSUE THREAD

**Issue by Shougo** [tyru/open-browser.vim#67]
https://github.com/tyru/open-browser.vim/blob/master/doc/openbrowser.txt#L281

restart.vim にも同じタグが含まれているので、neobundle で open-browser.vim をインストールし、`NeoBundleDocs` を実行するとタグの重複エラーになります。
おそらく、コピペミスでしょうか。

**Comment by tyru** [comment]
ありがとうございます。修正しました。
（一回Web UIで直そうとしたら間違ってEnter押してコミットしてしまった…）

**Comment by Shougo** [comment]
修正ありがとうございます
