### ISSUE TITLE
Linux(xdg-open) + chromium won't work

### ISSUE THREAD

**Issue by tyru** [tyru/open-browser.vim#68]
<https://twitter.com/mattn_jp/status/530026255412772864>

> @tyru openbrowser なんですが、ブラウザを起動していない状態で実行するとバックグラウンドで実行されない様です。Linux(xdg-open) で chromium です。

**Comment by tyru** [comment]
@mattn この件、設定まだ残ってたらいただけますか？

**Comment by mattn** [comment]
```
nmap <leader>G <Plug>(openbrowser-open)
```
設定これだけです。
以下、際限方法。

1. chromiumを起動していない状態にする
2. vim を起動して http://www.google.com/ を入力
3. URLの上で`<leader>G` をタイプ

この時点でvimに制御が戻っていないです。その後、chromiumで開いたタブ**以外のタブ**を全て閉じ、vimでCTRL-Cをタイプするとchromiumが終了します。

**Comment by tyru** [comment]
了解です。
調べてみます。
ありがとうございます。

**Comment by tyru** [comment]
修正しました。
報告ありがとうございました。
