### ISSUE TITLE
How to add to default search engines

### ISSUE THREAD

**Issue by spamwax** [tyru/open-browser.vim#69]
How can I add [DevDocs](http://devdocs.io) as the default search engine to this plugin?

That would help me write a map to search the documentations for the word under cursor by sending something like this to browser:
```
http://devdocs.io/#q=query
```

**Comment by tyru** [comment]
You can add like this.
```viml
    let g:openbrowser_search_engines = {
    \   'favorite': 'http://example.com/search?q={query}',
    \}
```

The default values are added if keys are absent.
So you don't have to concern about missing default values (`:help g:openbrowser_search_engines`).

However, I added DevDocs to default search engines just now.
You can use after `git pull` :)

**Comment by spamwax** [comment]
Thanks for explanation and the new commit :)
