### ISSUE TITLE
Links between '

### ISSUE THREAD

**Issue by adelarsq** [tyru/open-browser.vim#72]
After the commit ce1a1dc this plugin don't work with links between ':
```Plugin 'https://github.com/Lokaltog/vim-easymotion'```

![image](https://cloud.githubusercontent.com/assets/430272/9016626/f0de32d2-37a8-11e5-92d5-526a37ff5b2a.png)

**Comment by tyru** [comment]
Okay, the reason of #72 and #73 and #74 are the same. Fixed it.
Thanks for the report!

**Comment by BohrShaw** [comment]
@tyru It still gets wrong on `'http://www.example.com'`, but not `'http://www.example.com/'`.

**Comment by tyru** [comment]
@BohrShaw Fixed. thanks!
