### ISSUE TITLE
Support for Markdown links missing.

### ISSUE THREAD

**Issue by serge-stroobandt** [tyru/open-browser.vim#73]
Support for Markdown [links](https://daringfireball.net/projects/markdown/syntax#link) and [automatic links](https://daringfireball.net/projects/markdown/syntax#autolink) is missing.

The right parenthesis `)`, respectively right tag symbol `>` at the end of Markdown links are incorrectly included with the URL sent to the browser.

    [Markdown link](https://en.wikipedia.org/wiki/Markdown)

    <https://en.wikipedia.org/wiki/Markdown>

These symbols should be filtered out as URLs never contain them.

**Comment by tyru** [comment]
Okay, the reason of #72 and #73 and #74 are the same. Fixed it.
Thanks for the report!

**Comment by serge-stroobandt** [comment]
Works fine now in Markdown. Cheers mate!
For the curious ---and as a reference to myself,--- here is `$MYVIMRC` snippet:

    let g:netrw_nogx = 1    " disable netrw's gx mapping.
    nmap gx <Plug>(openbrowser-smart-search)
    vmap gx <Plug>(openbrowser-smart-search)

**Comment by tyru** [comment]
Your welcome :)
