### ISSUE TITLE
<Plug>(openbrowser-smart-search) can't use for searching word on web

### ISSUE THREAD

**Issue by toshi32tony3** [tyru/open-browser.vim#79]
2016/01/12 22:30最新のコードで\<Plug\>(openbrowser-smart-search)を使用した時、
指定した文字列を常にURIとして開こうとしてしまっています。

v0.1.1時点では、URI以外は既定のブラウザによる検索ができています。
いつ頃からかを特定できていないのですが、取り急ぎ報告させていただきます。

**Comment by toshi32tony3** [comment]
最新のコミットで修正されていることを確認しました。タイミング悪くすみません。クローズします。

**Comment by tyru** [comment]
確認ありがとうございました。
