### ISSUE TITLE
':OpenBrowserSmartSearch tyru/open-browser.vim' fails

### ISSUE THREAD

**Issue by tyru** [tyru/open-browser.vim#81]
via #80 (Cc: @toshi32tony3)

> こっちを取るとあっちが…という件かもですが、マージ後にSmartSearchの挙動が変わりました。
> 例えば、以下のコマンドを打つとURIとして認識してしまい、検索できなくなってしまいました。
> 
> > :OpenBrowserSmartSearch tyru/open-browser.vim

**Comment by toshi32tony3** [comment]
issue移行、ありがとうございます。

URI定義の正規表現にマッチするか否かで判定できると思いました。
が、ググってみたら、厳密なやつって長ったらしいんですね…。

> http://sinya8282.sakura.ne.jp/?p=1064

シンプルにURIスキームが付いてるか否か判定するで良い気もします。

**Comment by tyru** [comment]
ありがとうございます。
修正しました。

**Comment by toshi32tony3** [comment]
対応ありがとうございます！修正されていることを確認しました。
