### ISSUE TITLE
After visual map executes, it doesn't stay in visual mode

### ISSUE THREAD

**Issue by grr** [tyru/open-browser.vim#94]
I'm using the default maps as documented. After selecting text in visual mode and using the map, the mode is changed to normal mode. It should stay in visual mode.

Also, can you allow an easier way to silence the plugin messages? Currently the only way to do so is using an obscure syntax:

    nnoremap <silent> gx :silent execute "normal \<Plug>(openbrowser-open)"<CR>
    vnoremap <silent> gx :<C-u>silent execute "normal \<Plug>(openbrowser-open)"<CR>

If not, can you at least document those mappings. Thanks.

**Comment by tyru** [comment]
> can you allow an easier way to silence the plugin messages?

Try

```viml
let g:openbrowser_format_message = ''
```

See this:
https://github.com/tyru/open-browser.vim/blob/2780c6858d921271afbf001582405a2494fd51ca/doc/openbrowser.txt#L303-L304

> It should stay in visual mode.

Hmm, I can't imagine such use case why it should stay in visual mode.
I think it's enough to use `gv` mapping, isn't it?

```viml
vmap gx <Plug>(openbrowser-open)gv
```

**Comment by grr** [comment]
> let g:openbrowser_format_message = ''

That only silences the Opening url message. But if you get the error message "URL of file path is not found under cursor!", even after successfully opening a url afterwards the error stays. I want to silence those errors also.

**Comment by tyru** [comment]
Currently there are no ways to silence error messages.
Could you checkout #95 branch and `let g:openbrowser_message_verbosity = 0`?

**Comment by grr** [comment]
That new flag is perfect. Tested and no problems.

**Comment by tyru** [comment]
@grr Thanks for testing! merged the branch.
