### ISSUE TITLE
The text "foo bar: baz" is mis-opened as "foo://bar"

### ISSUE THREAD

**Issue by bohrshaw** [tyru/open-browser.vim#96]

**Comment by tyru** [comment]
Please give me the steps to reproduce.
what mapping did you execute?

**Comment by bohrshaw** [comment]
Oh, it's `<Plug>(openbrowser-smart-search)`

**Comment by tyru** [comment]
Got it.
Could you try this branch? #97

**Comment by bohrshaw** [comment]
It works.

**Comment by tyru** [comment]
@bohrshaw Thanks! 😄
